# Source: bucketrepo/templates/config-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: bucketrepo-config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
stringData:
  config.yaml: |
    http:
        addr: ":8080"
        username: "todo"
        password: "todo"
        chartPath: "charts"

    storage:
        bucket_url: ""

    cache:
        base_dir: "/tmp/bucketrepo"

    repositories:
        - url: "https://repo.maven.org/maven2"
        - url: "https://repo1.maven.org/maven2"
        - url: "https://services.gradle.org/distributions/"
        - url: "https://plugins.gradle.org/m2/"
        - url: "https://repo.jenkins-ci.org/public/"
        - url: "https://repo.jenkins-ci.org/releases/"
        - url: "https://jitpack.io/"
        - url: "https://registry.npmjs.org/"
        - url: "https://repo.spring.io/milestone/"
        - url: "https://repo.spring.io/release/"
        - url: "http://uk.maven.org/maven2/"
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: secret-infra
  data: []
  template:
    metadata:
      annotations:
        config/checksum: c41b5c22daadb25e478a6d0f1ccf4d8fd388a3851bc559a9adf789d902fe80b0
    type: Opaque
