# Source: docker-registry/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: docker-registry-secret
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: vault-infra
  data:
  - name: haSharedSecret
    key: secret/data/docker/registry/secret
    property: haSharedSecret
  template:
    metadata:
      labels:
        app: docker-registry
        chart: docker-registry-1.9.4
        heritage: Helm
        release: docker-registry
    type: Opaque
